[project]
name = "venv-project"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy[asyncio]",
    "alembic",
    "pydantic-settings",
    "python-jose[cryptography]",
    "pyjwt[crypto]",
    "python-multipart",
    "asyncpg>=0.31.0",
    "types-passlib==1.7.7.20260211",
    "psycopg[binary]",
    "pwdlib[bcrypt]",
]

[tool.mypy]
plugins = ["pydantic.mypy"]

