"""initial database

Revision ID: 7ce54f2fd2d2
Revises: 
Create Date: 2026-09-12 14:16:05.859321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce54f2fd2d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_devices',
    sa.Column('iot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iot_firmware_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('iot_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('iot_device_sensors',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('iot_device_id', sa.UUID(), nullable=False),
    sa.Column('sensor_name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['iot_device_id'], ['iot_devices.iot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('sensor_snapshots',
    sa.Column('snapshots_id', sa.UUID(), nullable=False),
    sa.Column('iot_device_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=False),
    sa.Column('fuzzy_value', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iot_device_id'], ['iot_devices.iot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['iot_device_sensors.sensor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshots_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_snapshots')
    op.drop_table('iot_device_sensors')
    op.drop_table('users')
    op.drop_table('iot_devices')
    # ### end Alembic commands ###
