"""add references from iot`s to user

Revision ID: ae36c4472c96
Revises: 7ce54f2fd2d2
Create Date: 2026-09-16 19:47:39.057490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae36c4472c96'
down_revision: Union[str, None] = '7ce54f2fd2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iot_devices', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'iot_devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'iot_devices', type_='foreignkey')
    op.drop_column('iot_devices', 'user_id')
    # ### end Alembic commands ###
